<?php include 'components/head.php'; ?>
<?php include 'components/navbar.php'; ?>


<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand1.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand2.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand3.jpg" alt="main magique" class="imghand">
<img src="../assets/img/header/hand4.jpg" alt="main magique" class="imghand">
<?php include 'components/footer.php'; ?>